### PR TITLE
Removing GraphQL spec 

### PR DESCRIPTION
**Pull request by wtrocki**
This is not used. Creating as separate PR

### CODE REVIEW

**Comment by ralfhandl** [comment]
@wtrocki website seems to not have been updated, http://rapid.rocks/docs/rsdl/ is still there.

**Comment by wtrocki** [comment]
Going to push this soon. I see that actual RDSL was also not included

**Comment by wtrocki** [comment]
Not on computer right now. Anyone should be able to publish now.. I have resolved build issues

**Comment by ralfhandl** [comment]
Worked :-)

**Pull request merged**
