### PR TITLE
project root is monorepo

### PR DESCRIPTION
**Pull request by ralfhandl**
- move monorepo setup and config files from tools to project root
- add website to monorepo
- update rsdl-js to ANTLR 4.9.2
- clean tools folder after install

### CODE REVIEW

**Comment by mikepizzo** [comment]
I get the following errors when I try to do npm run build:

Node.js v18.1.0
npm ERR! Lifecycle script `antlr4ts` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: odata-uri@1.0.0
npm ERR!   at location: c:\Repos\Rapid\odata-rapid-root-monorepo\tools\odataUri
npm ERR! Lifecycle script `build` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: odata-uri@1.0.0
npm ERR!   at location: c:\Repos\Rapid\odata-rapid-root-monorepo\tools\odataUri

**Review by mikepizzo — CHANGES_REQUESTED** [review]
I am getting build issues, apparently related to Antlr, when building from root or tools.

**Comment by ralfhandl** [comment]
I did a clean checkout, switched to this branch, then in the project root
- npm install
- npm run build

Ran through without problems in PowerShell 7.2.6 and cmd.

**Comment by ralfhandl** [comment]
> Error: spawn java ENOENT

@mikepizzo Can you please check whether you have Java installed and in the path?

In your `pwsh` type
~~~pwsh
java -version
~~~

**Review by mikepizzo — APPROVED** [review]
Installing Java worked. Interesting that it was never an issue when building directly from the tools folder.

**Comment by ralfhandl** [comment]
Reason was that the old build script did not compile the URL ABNF to TypeScript, this needed to be done manually.

**Pull request merged**
