### PR TITLE
add logo, update version

### PR DESCRIPTION
**Pull request by chrisspre**
- docusaurus version updated to "2.0.0-alpha.75",
- logo is added as svg

open issues. 
- problem with changing small icon in top left (just replacing logo.svg with rabbit.svg is not working.
- placement of large logo in center needs more css finesse

### CODE REVIEW

**Review by ralfhandl — APPROVED** [review]

**Comment by mikepizzo** [comment]
Fixes #239 
Fixes #240

**Comment by chrisspre** [comment]
image

**Review by mikepizzo — APPROVED** [review]
:shipit:

**Comment by chrisspre** [comment]
@ralfhandl @mikepizzo do you know what has to be done to publish the changes?

**Comment by chrisspre** [comment]
Thanks Ralf.

**Pull request merged**
