### PR TITLE
add name property to service RDM element and use in transformation

### LINKED ISSUE #121: Allow to name the service in RSDL

### PR DESCRIPTION
**Pull request by chrisspre**
fixes #121

### CODE REVIEW

**Comment by ralfhandl** [comment]
I'd like to keep services "nameless" and close this PR without merging it

**Review by ralfhandl — CHANGES_REQUESTED** [review]
Please close without merging

**Comment by chrisspre** [comment]
> Please close without merging

@mikepizzo you gave the service a name in the intro document. I am ok with unnamed service but wanted to give you a chance to chime in.

**Comment by chrisspre** [comment]
> > Please close without merging
> 
> @mikepizzo you gave the service a name in the intro document. I am ok with unnamed service but wanted to give you a chance to chime in.

Spoke to Mike and I am going to abandon this PR.

**Pull request closed without merging**
