### PR TITLE
Fix website SSR issues

### PR DESCRIPTION
**Pull request by wtrocki**
Building SSR was failing. Added some checks.

Website is available for preview on:
https://oasis-open.github.io/odata-rapid/

@sthagen We need to remove the domain from your private repo to enable it here

### CODE REVIEW

**Comment by sthagen** [comment]
@wtrocki @ralfhandl @chet-ensign welcome to point to https://rapid.rocks via settings now.

**Comment by wtrocki** [comment]
Awesome! I'm trying it now.

@sthagen do you have any other domains registered?
What's is provider?
rapid.rocks sounds more like concrete company than tech. Any com. dev. org. will be more desired

**Comment by wtrocki** [comment]
I have swapped URL, however rocks domain is very problematic. 
It is not possible to setup HTTPS for it using automation etc.

`Error: Certbot is not working with .rocks domain`

It will be probably required to pay for it.. 
My strong recommendation would be to buy another domain that is more common etc.

CC  @mikepizzo @ralfhandl

**Comment by sthagen** [comment]
I think their will be a solution with the domain. Why should there be an automation problem we cannot rapidly solve?

**Comment by wtrocki** [comment]
I think we need admin to check it as I did not seen option to `enforce https` on Github. 
Tried to request it myself and include that into repository but that did not work.

**Comment by sthagen** [comment]
What I wanted to emphasize is, I checked with the private repo already that rapid.rocks just works - albeit the weak https implementation on github side. The cloudflare stuff is rock solid. And, unless we give up, rapid rocks 😉

**Comment by ralfhandl** [comment]
+1, I love rapid.rocks :smile:

**Comment by wtrocki** [comment]
I will stick to GitHub for simplicity. We need just admin to request https cert and we are sorted

**Pull request merged**
